/**
 * Tier 2: the TypeScript implementations against scikit-bio and scipy.
 *
 * The fixture is generated by scripts/reference.py. Regenerate it with
 * `.venv/bin/python scripts/reference.py` after changing the dataset.
 *
 * This is the test that catches the mistakes closed-form cases cannot: a log
 * base that disagrees with `vegan`, a Simpson index reported in the wrong
 * direction, a rarefaction curve off by one ticket.
 */

import { describe, expect, test } from 'vitest';
import { allShops, countMatrix, countVector, shopById } from '../data/index';
import {
	giniSimpson,
	goodsCoverage,
	invSimpson,
	observedRichness,
	pielou,
	rarefactionCurve,
	shannon,
	simpson
} from './alpha';
import { brayCurtis, distanceMatrix, jaccard, relativeAbundance } from './beta';
import { pcoa } from './ordination';
import fixture from './fixtures/reference.json';

const TOLERANCE = 10;

const table = countMatrix(allShops);

describe('the fixture matches the dataset it was generated from', () => {
	test('covers every shop in the same order', () => {
		expect(fixture.shopIds).toEqual(allShops.map((s) => s.id));
	});

	test('was generated with a real scientific stack', () => {
		expect(fixture.versions['scikit-bio']).toBeTruthy();
		expect(fixture.versions.scipy).toBeTruthy();
	});
});

describe('alpha diversity agrees with scikit-bio', () => {
	const entries = Object.entries(fixture.alpha);

	test.each(entries)('%s', (shopId, expected) => {
		const counts = countVector(shopById.get(shopId)!);

		expect(observedRichness(counts)).toBeCloseTo(expected.observedRichness, TOLERANCE);
		expect(shannon(counts)).toBeCloseTo(expected.shannon, TOLERANCE);
		expect(pielou(counts)).toBeCloseTo(expected.pielou, TOLERANCE);
		expect(goodsCoverage(counts)).toBeCloseTo(expected.goodsCoverage, TOLERANCE);
		expect(invSimpson(counts)).toBeCloseTo(expected.invSimpson, TOLERANCE);

		// skbio calls sum(p^2) `dominance` and reserves `simpson` for 1 - sum(p^2).
		// This project uses the ecology-textbook naming, so the two are crossed
		// here on purpose.
		expect(simpson(counts)).toBeCloseTo(expected.dominance, TOLERANCE);
		expect(giniSimpson(counts)).toBeCloseTo(expected.giniSimpson, TOLERANCE);
	});
});

describe('rarefaction agrees with the Hurlbert expectation', () => {
	const { depths, expected } = fixture.rarefaction;

	test.each(Object.entries(expected))('%s', (shopId, values) => {
		const counts = countVector(shopById.get(shopId)!);
		const curve = rarefactionCurve(counts, { step: 1 });
		const byDepth = new Map(curve.map((p) => [p.depth, p.expectedRichness]));

		values.forEach((value, i) => {
			expect(byDepth.get(depths[i])).toBeCloseTo(value, TOLERANCE);
		});
	});
});

describe('beta diversity agrees with scipy', () => {
	test('Bray-Curtis on raw counts', () => {
		const mine = distanceMatrix(table, brayCurtis);
		for (let i = 0; i < table.length; i++) {
			for (let j = 0; j < table.length; j++) {
				expect(mine[i][j]).toBeCloseTo(fixture.beta.brayCurtis[i][j], TOLERANCE);
			}
		}
	});

	test('Bray-Curtis on relative abundances', () => {
		const mine = distanceMatrix(table.map(relativeAbundance), brayCurtis);
		for (let i = 0; i < table.length; i++) {
			for (let j = 0; j < table.length; j++) {
				expect(mine[i][j]).toBeCloseTo(fixture.beta.brayCurtisRelative[i][j], TOLERANCE);
			}
		}
	});

	test('Jaccard on presence and absence', () => {
		const mine = distanceMatrix(table, jaccard);
		for (let i = 0; i < table.length; i++) {
			for (let j = 0; j < table.length; j++) {
				expect(mine[i][j]).toBeCloseTo(fixture.beta.jaccard[i][j], TOLERANCE);
			}
		}
	});

	test("the Vinnie's pair is 0 by Jaccard and 0.79 by Bray-Curtis", () => {
		expect(fixture.scipySpotChecks.jaccardVinniesUptown).toBe(0);
		expect(fixture.scipySpotChecks.brayCurtisVinniesUptownRelative).toBeCloseTo(0.789, 3);
	});
});

describe('PCoA agrees with scikit-bio', () => {
	const mine = pcoa(distanceMatrix(table, brayCurtis));
	const expectedEigenvalues = fixture.pcoa.eigenvalues;

	test('reproduces every positive eigenvalue scikit-bio reports', () => {
		// skbio zeroes the negative tail rather than reporting it, so the two
		// arrays agree exactly over the positive block and then diverge.
		const positive = expectedEigenvalues.filter((v) => v > 1e-9);
		expect(positive.length).toBeGreaterThan(20);

		for (let k = 0; k < positive.length; k++) {
			expect(mine.eigenvalues[k]).toBeCloseTo(positive[k], 8);
		}
	});

	test('carries only non-positive eigenvalues past that block', () => {
		const positive = expectedEigenvalues.filter((v) => v > 1e-9).length;
		for (let k = positive; k < mine.eigenvalues.length; k++) {
			expect(mine.eigenvalues[k]).toBeLessThan(1e-9);
		}
	});

	test('reproduces its proportion explained', () => {
		const expected = fixture.pcoa.proportionExplained;
		for (let k = 0; k < expected.length; k++) {
			expect(mine.varianceExplained[k]).toBeCloseTo(expected[k], 8);
		}
	});

	test('also reports the negative eigenvalues scikit-bio only warns about', () => {
		expect(mine.eigenvalues.some((v) => v < -1e-6)).toBe(true);
		expect(mine.negativeFraction).toBeGreaterThan(0);
	});
});
