"""Cross-language reference values for the diversity metrics.

Computes alpha and beta diversity on the real pizzeria count table using
scikit-bio and scipy, then writes tests/fixtures/reference.json. The TypeScript
implementations in src/lib/diversity are asserted against this file, so a naming
or normalisation mistake shows up as a test failure rather than as a wrong
number on the page.

Run with:  .venv/bin/python scripts/reference.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from scipy.spatial.distance import braycurtis, jaccard
from skbio.diversity import beta_diversity
from skbio.diversity.alpha import (
    dominance,
    enspie,
    goods_coverage,
    observed_features,
    pielou_e,
    shannon,
    simpson,
)
from skbio.stats.ordination import pcoa

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "lib" / "data"
FIXTURES = ROOT / "src" / "lib" / "diversity" / "fixtures"


def load() -> tuple[list[str], list[str], np.ndarray]:
    pizza_ids = [p["id"] for p in json.loads((DATA / "pizzas.json").read_text())["pizzas"]]
    shops = (
        json.loads((DATA / "heroes.json").read_text())["shops"]
        + json.loads((DATA / "field.json").read_text())["shops"]
    )
    index = {pid: i for i, pid in enumerate(pizza_ids)}

    table = np.zeros((len(shops), len(pizza_ids)), dtype=np.int64)
    for row, shop in enumerate(shops):
        for pid, count in shop["counts"].items():
            table[row, index[pid]] = count

    return [s["id"] for s in shops], pizza_ids, table


def rarefaction(counts: np.ndarray, depths: list[int]) -> list[float]:
    """Hurlbert's expected species richness, via log-gamma for stability."""
    from scipy.special import gammaln

    observed = counts[counts > 0].astype(float)
    n = float(counts.sum())

    def log_choose(a: float, b: float) -> float:
        return gammaln(a + 1) - gammaln(b + 1) - gammaln(a - b + 1)

    out = []
    for depth in depths:
        total = 0.0
        for x in observed:
            remaining = n - x
            if remaining < depth:
                total += 1.0
            else:
                total += 1.0 - np.exp(log_choose(remaining, depth) - log_choose(n, depth))
        out.append(float(total))
    return out


def main() -> None:
    shop_ids, pizza_ids, table = load()

    alpha = {}
    for shop_id, counts in zip(shop_ids, table):
        alpha[shop_id] = {
            # skbio's `simpson` is the Gini-Simpson form, 1 - sum(p^2); the
            # sum-of-squares form it calls `dominance`. Both are checked so the
            # TypeScript naming cannot drift from the tool the reader will use.
            "observedRichness": float(observed_features(counts)),
            "shannon": float(shannon(counts, base=np.e)),
            "dominance": float(dominance(counts)),
            "giniSimpson": float(simpson(counts)),
            "invSimpson": float(enspie(counts)),
            "pielou": float(pielou_e(counts)),
            "goodsCoverage": float(goods_coverage(counts)),
        }

    hero_ids = shop_ids[:5]
    rarefaction_depths = [1, 5, 10, 20, 30, 34]
    rarefied = {
        shop_id: rarefaction(counts, [d for d in rarefaction_depths if d <= counts.sum()])
        for shop_id, counts in zip(hero_ids, table[:5])
    }

    bray = beta_diversity("braycurtis", table, ids=shop_ids)
    jac = beta_diversity("jaccard", table, ids=shop_ids)

    relative = table / table.sum(axis=1, keepdims=True)
    bray_relative = np.array(
        [[braycurtis(a, b) for b in relative] for a in relative], dtype=float
    )

    ordination = pcoa(bray, method="eigh", number_of_dimensions=0)

    fixture = {
        "$comment": (
            "Generated by scripts/reference.py using scikit-bio and scipy. "
            "Do not edit by hand."
        ),
        "shopIds": shop_ids,
        "pizzaIds": pizza_ids,
        "alpha": alpha,
        "rarefaction": {
            "depths": rarefaction_depths,
            "expected": rarefied,
        },
        "beta": {
            "brayCurtis": bray.data.tolist(),
            "jaccard": jac.data.tolist(),
            "brayCurtisRelative": bray_relative.tolist(),
        },
        "pcoa": {
            "eigenvalues": ordination.eigvals.to_numpy().tolist(),
            "proportionExplained": ordination.proportion_explained.to_numpy().tolist(),
        },
        "scipySpotChecks": {
            "brayCurtisVinniesUptownRelative": float(braycurtis(relative[0], relative[4])),
            "jaccardVinniesUptown": float(
                jaccard(table[0] > 0, table[4] > 0)
            ),
        },
        "versions": {},
    }

    import scipy
    import skbio

    fixture["versions"] = {"scipy": scipy.__version__, "scikit-bio": skbio.__version__}

    FIXTURES.mkdir(parents=True, exist_ok=True)
    out = FIXTURES / "reference.json"
    out.write_text(json.dumps(fixture, indent=1) + "\n")
    print(f"wrote {out.relative_to(ROOT)}")
    print(f"  {len(shop_ids)} shops, {len(pizza_ids)} pizza types")
    print(f"  scipy {scipy.__version__}, scikit-bio {skbio.__version__}")


if __name__ == "__main__":
    main()
